version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: momentum_trading
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: your_password
    volumes:
      - ./resources/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
